name: Python CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Project
              uses: actions/checkout@v4

            - name: Configurar python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Instalar dependencies
              run: pip install -r requirements.txt

            - name: Run
              run: pytest test_main.py

            - name: Exito
              run: python -c "print('Compilación exitosa')"
