name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Hacer checkout del proyecto
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verificar dependencias instaladas
      run: pip freeze

    - name: Ejecutar pruebas
      run: pytest test_main.py

    - name: Compilación exitosa
      if: success()
      run: echo "compilación exitosa"

